baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[params]
  org = "Evaluation Center"
  logoUrl =  "/img/logos/EC_logo.png"
  title= "Evaluation Center"
  subtitle= "at Northwestern University"
